# Generated by Django 6.1.1 on 2026-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_bb_is_active_alter_bb_content_alter_bb_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.SmallIntegerField(choices=[(1, 'Куплю'), (2, 'Продам'), (3, 'Обменяю'), (4, 'Rent')], default=2),
        ),
    ]
