# Generated by Django 6.1.1 on 2026-09-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_measure_spare_advuser_machine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to='rubric',
        ),
    ]
